# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lte/protos/oai/ngap_state.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lte/protos/oai/ngap_state.proto',
  package='magma.lte.oai',
  syntax='proto3',
  serialized_options=b'Z\035magma/lte/cloud/go/protos/oai',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1flte/protos/oai/ngap_state.proto\x12\rmagma.lte.oai\"$\n\tNgapTimer\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03sec\x18\x02 \x01(\x05\"\xba\x02\n\x0eGnbDescription\x12\x0e\n\x06gnb_id\x18\x01 \x01(\r\x12\x10\n\x08ng_state\x18\x02 \x01(\x05\x12\x10\n\x08gnb_name\x18\x03 \x01(\x0c\x12\x1a\n\x12\x64\x65\x66\x61ult_paging_drx\x18\x04 \x01(\r\x12\x18\n\x10nb_ue_associated\x18\x05 \x01(\r\x12\x15\n\rsctp_assoc_id\x18\x06 \x01(\r\x12\x18\n\x10next_sctp_stream\x18\x07 \x01(\r\x12\x11\n\tinstreams\x18\x08 \x01(\r\x12\x12\n\noutstreams\x18\t \x01(\r\x12\x38\n\x06ue_ids\x18\n \x03(\x0b\x32(.magma.lte.oai.GnbDescription.UeIdsEntry\x1a,\n\nUeIdsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12\r\n\x05value\x18\x02 \x01(\x04:\x02\x38\x01\"\xe1\x01\n\x12Ngap_UeDescription\x12\x13\n\x0bng_ue_state\x18\x02 \x01(\x05\x12\x16\n\x0egnb_ue_ngap_id\x18\x03 \x01(\r\x12\x16\n\x0e\x61mf_ue_ngap_id\x18\x04 \x01(\r\x12\x18\n\x10sctp_stream_recv\x18\x05 \x01(\r\x12\x18\n\x10sctp_stream_send\x18\x06 \x01(\r\x12;\n\x19ngap_ue_context_rel_timer\x18\x07 \x01(\x0b\x32\x18.magma.lte.oai.NgapTimer\x12\x15\n\rsctp_assoc_id\x18\x08 \x01(\r\"\x95\x02\n\tNgapState\x12\x30\n\x04gnbs\x18\x01 \x03(\x0b\x32\".magma.lte.oai.NgapState.GnbsEntry\x12\x42\n\ramfid2associd\x18\x02 \x03(\x0b\x32+.magma.lte.oai.NgapState.Amfid2associdEntry\x12\x10\n\x08num_gnbs\x18\x03 \x01(\r\x1aJ\n\tGnbsEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x1d.magma.lte.oai.GnbDescription:\x02\x38\x01\x1a\x34\n\x12\x41mfid2associdEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\"\x90\x01\n\x0bNgapImsiMap\x12J\n\x12\x61mf_ue_id_imsi_map\x18\x01 \x03(\x0b\x32..magma.lte.oai.NgapImsiMap.AmfUeIdImsiMapEntry\x1a\x35\n\x13\x41mfUeIdImsiMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12\r\n\x05value\x18\x02 \x01(\x04:\x02\x38\x01\x42\x1fZ\x1dmagma/lte/cloud/go/protos/oaib\x06proto3'
)




_NGAPTIMER = _descriptor.Descriptor(
  name='NgapTimer',
  full_name='magma.lte.oai.NgapTimer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='magma.lte.oai.NgapTimer.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sec', full_name='magma.lte.oai.NgapTimer.sec', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=86,
)


_GNBDESCRIPTION_UEIDSENTRY = _descriptor.Descriptor(
  name='UeIdsEntry',
  full_name='magma.lte.oai.GnbDescription.UeIdsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='magma.lte.oai.GnbDescription.UeIdsEntry.key', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='magma.lte.oai.GnbDescription.UeIdsEntry.value', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=359,
  serialized_end=403,
)

_GNBDESCRIPTION = _descriptor.Descriptor(
  name='GnbDescription',
  full_name='magma.lte.oai.GnbDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gnb_id', full_name='magma.lte.oai.GnbDescription.gnb_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ng_state', full_name='magma.lte.oai.GnbDescription.ng_state', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gnb_name', full_name='magma.lte.oai.GnbDescription.gnb_name', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='default_paging_drx', full_name='magma.lte.oai.GnbDescription.default_paging_drx', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nb_ue_associated', full_name='magma.lte.oai.GnbDescription.nb_ue_associated', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sctp_assoc_id', full_name='magma.lte.oai.GnbDescription.sctp_assoc_id', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='next_sctp_stream', full_name='magma.lte.oai.GnbDescription.next_sctp_stream', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='instreams', full_name='magma.lte.oai.GnbDescription.instreams', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='outstreams', full_name='magma.lte.oai.GnbDescription.outstreams', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ue_ids', full_name='magma.lte.oai.GnbDescription.ue_ids', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_GNBDESCRIPTION_UEIDSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=403,
)


_NGAP_UEDESCRIPTION = _descriptor.Descriptor(
  name='Ngap_UeDescription',
  full_name='magma.lte.oai.Ngap_UeDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ng_ue_state', full_name='magma.lte.oai.Ngap_UeDescription.ng_ue_state', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gnb_ue_ngap_id', full_name='magma.lte.oai.Ngap_UeDescription.gnb_ue_ngap_id', index=1,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='amf_ue_ngap_id', full_name='magma.lte.oai.Ngap_UeDescription.amf_ue_ngap_id', index=2,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sctp_stream_recv', full_name='magma.lte.oai.Ngap_UeDescription.sctp_stream_recv', index=3,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sctp_stream_send', full_name='magma.lte.oai.Ngap_UeDescription.sctp_stream_send', index=4,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ngap_ue_context_rel_timer', full_name='magma.lte.oai.Ngap_UeDescription.ngap_ue_context_rel_timer', index=5,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sctp_assoc_id', full_name='magma.lte.oai.Ngap_UeDescription.sctp_assoc_id', index=6,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=631,
)


_NGAPSTATE_GNBSENTRY = _descriptor.Descriptor(
  name='GnbsEntry',
  full_name='magma.lte.oai.NgapState.GnbsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='magma.lte.oai.NgapState.GnbsEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='magma.lte.oai.NgapState.GnbsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=783,
  serialized_end=857,
)

_NGAPSTATE_AMFID2ASSOCIDENTRY = _descriptor.Descriptor(
  name='Amfid2associdEntry',
  full_name='magma.lte.oai.NgapState.Amfid2associdEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='magma.lte.oai.NgapState.Amfid2associdEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='magma.lte.oai.NgapState.Amfid2associdEntry.value', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=859,
  serialized_end=911,
)

_NGAPSTATE = _descriptor.Descriptor(
  name='NgapState',
  full_name='magma.lte.oai.NgapState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gnbs', full_name='magma.lte.oai.NgapState.gnbs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='amfid2associd', full_name='magma.lte.oai.NgapState.amfid2associd', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_gnbs', full_name='magma.lte.oai.NgapState.num_gnbs', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_NGAPSTATE_GNBSENTRY, _NGAPSTATE_AMFID2ASSOCIDENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=634,
  serialized_end=911,
)


_NGAPIMSIMAP_AMFUEIDIMSIMAPENTRY = _descriptor.Descriptor(
  name='AmfUeIdImsiMapEntry',
  full_name='magma.lte.oai.NgapImsiMap.AmfUeIdImsiMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='magma.lte.oai.NgapImsiMap.AmfUeIdImsiMapEntry.key', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='magma.lte.oai.NgapImsiMap.AmfUeIdImsiMapEntry.value', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1005,
  serialized_end=1058,
)

_NGAPIMSIMAP = _descriptor.Descriptor(
  name='NgapImsiMap',
  full_name='magma.lte.oai.NgapImsiMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='amf_ue_id_imsi_map', full_name='magma.lte.oai.NgapImsiMap.amf_ue_id_imsi_map', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_NGAPIMSIMAP_AMFUEIDIMSIMAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=914,
  serialized_end=1058,
)

_GNBDESCRIPTION_UEIDSENTRY.containing_type = _GNBDESCRIPTION
_GNBDESCRIPTION.fields_by_name['ue_ids'].message_type = _GNBDESCRIPTION_UEIDSENTRY
_NGAP_UEDESCRIPTION.fields_by_name['ngap_ue_context_rel_timer'].message_type = _NGAPTIMER
_NGAPSTATE_GNBSENTRY.fields_by_name['value'].message_type = _GNBDESCRIPTION
_NGAPSTATE_GNBSENTRY.containing_type = _NGAPSTATE
_NGAPSTATE_AMFID2ASSOCIDENTRY.containing_type = _NGAPSTATE
_NGAPSTATE.fields_by_name['gnbs'].message_type = _NGAPSTATE_GNBSENTRY
_NGAPSTATE.fields_by_name['amfid2associd'].message_type = _NGAPSTATE_AMFID2ASSOCIDENTRY
_NGAPIMSIMAP_AMFUEIDIMSIMAPENTRY.containing_type = _NGAPIMSIMAP
_NGAPIMSIMAP.fields_by_name['amf_ue_id_imsi_map'].message_type = _NGAPIMSIMAP_AMFUEIDIMSIMAPENTRY
DESCRIPTOR.message_types_by_name['NgapTimer'] = _NGAPTIMER
DESCRIPTOR.message_types_by_name['GnbDescription'] = _GNBDESCRIPTION
DESCRIPTOR.message_types_by_name['Ngap_UeDescription'] = _NGAP_UEDESCRIPTION
DESCRIPTOR.message_types_by_name['NgapState'] = _NGAPSTATE
DESCRIPTOR.message_types_by_name['NgapImsiMap'] = _NGAPIMSIMAP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NgapTimer = _reflection.GeneratedProtocolMessageType('NgapTimer', (_message.Message,), {
  'DESCRIPTOR' : _NGAPTIMER,
  '__module__' : 'lte.protos.oai.ngap_state_pb2'
  # @@protoc_insertion_point(class_scope:magma.lte.oai.NgapTimer)
  })
_sym_db.RegisterMessage(NgapTimer)

GnbDescription = _reflection.GeneratedProtocolMessageType('GnbDescription', (_message.Message,), {

  'UeIdsEntry' : _reflection.GeneratedProtocolMessageType('UeIdsEntry', (_message.Message,), {
    'DESCRIPTOR' : _GNBDESCRIPTION_UEIDSENTRY,
    '__module__' : 'lte.protos.oai.ngap_state_pb2'
    # @@protoc_insertion_point(class_scope:magma.lte.oai.GnbDescription.UeIdsEntry)
    })
  ,
  'DESCRIPTOR' : _GNBDESCRIPTION,
  '__module__' : 'lte.protos.oai.ngap_state_pb2'
  # @@protoc_insertion_point(class_scope:magma.lte.oai.GnbDescription)
  })
_sym_db.RegisterMessage(GnbDescription)
_sym_db.RegisterMessage(GnbDescription.UeIdsEntry)

Ngap_UeDescription = _reflection.GeneratedProtocolMessageType('Ngap_UeDescription', (_message.Message,), {
  'DESCRIPTOR' : _NGAP_UEDESCRIPTION,
  '__module__' : 'lte.protos.oai.ngap_state_pb2'
  # @@protoc_insertion_point(class_scope:magma.lte.oai.Ngap_UeDescription)
  })
_sym_db.RegisterMessage(Ngap_UeDescription)

NgapState = _reflection.GeneratedProtocolMessageType('NgapState', (_message.Message,), {

  'GnbsEntry' : _reflection.GeneratedProtocolMessageType('GnbsEntry', (_message.Message,), {
    'DESCRIPTOR' : _NGAPSTATE_GNBSENTRY,
    '__module__' : 'lte.protos.oai.ngap_state_pb2'
    # @@protoc_insertion_point(class_scope:magma.lte.oai.NgapState.GnbsEntry)
    })
  ,

  'Amfid2associdEntry' : _reflection.GeneratedProtocolMessageType('Amfid2associdEntry', (_message.Message,), {
    'DESCRIPTOR' : _NGAPSTATE_AMFID2ASSOCIDENTRY,
    '__module__' : 'lte.protos.oai.ngap_state_pb2'
    # @@protoc_insertion_point(class_scope:magma.lte.oai.NgapState.Amfid2associdEntry)
    })
  ,
  'DESCRIPTOR' : _NGAPSTATE,
  '__module__' : 'lte.protos.oai.ngap_state_pb2'
  # @@protoc_insertion_point(class_scope:magma.lte.oai.NgapState)
  })
_sym_db.RegisterMessage(NgapState)
_sym_db.RegisterMessage(NgapState.GnbsEntry)
_sym_db.RegisterMessage(NgapState.Amfid2associdEntry)

NgapImsiMap = _reflection.GeneratedProtocolMessageType('NgapImsiMap', (_message.Message,), {

  'AmfUeIdImsiMapEntry' : _reflection.GeneratedProtocolMessageType('AmfUeIdImsiMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _NGAPIMSIMAP_AMFUEIDIMSIMAPENTRY,
    '__module__' : 'lte.protos.oai.ngap_state_pb2'
    # @@protoc_insertion_point(class_scope:magma.lte.oai.NgapImsiMap.AmfUeIdImsiMapEntry)
    })
  ,
  'DESCRIPTOR' : _NGAPIMSIMAP,
  '__module__' : 'lte.protos.oai.ngap_state_pb2'
  # @@protoc_insertion_point(class_scope:magma.lte.oai.NgapImsiMap)
  })
_sym_db.RegisterMessage(NgapImsiMap)
_sym_db.RegisterMessage(NgapImsiMap.AmfUeIdImsiMapEntry)


DESCRIPTOR._options = None
_GNBDESCRIPTION_UEIDSENTRY._options = None
_NGAPSTATE_GNBSENTRY._options = None
_NGAPSTATE_AMFID2ASSOCIDENTRY._options = None
_NGAPIMSIMAP_AMFUEIDIMSIMAPENTRY._options = None
# @@protoc_insertion_point(module_scope)
