# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lte/protos/oai/sgw_state.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from lte.protos.oai import common_types_pb2 as lte_dot_protos_dot_oai_dot_common__types__pb2
from lte.protos.oai import std_3gpp_types_pb2 as lte_dot_protos_dot_oai_dot_std__3gpp__types__pb2
from lte.protos.oai import spgw_state_pb2 as lte_dot_protos_dot_oai_dot_spgw__state__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='lte/protos/oai/sgw_state.proto',
  package='magma.lte.oai',
  syntax='proto3',
  serialized_options=b'Z\035magma/lte/cloud/go/protos/oai',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1elte/protos/oai/sgw_state.proto\x12\rmagma.lte.oai\x1a!lte/protos/oai/common_types.proto\x1a#lte/protos/oai/std_3gpp_types.proto\x1a\x1flte/protos/oai/spgw_state.proto\"\xca\x02\n\x19SgwS8EpsBearerContextInfo\x12\x0c\n\x04imsi\x18\x01 \x01(\x0c\x12\x1d\n\x15imsi_unauth_indicator\x18\x02 \x01(\r\x12\x0e\n\x06msisdn\x18\x03 \x01(\t\x12/\n\x12last_known_cell_id\x18\x04 \x01(\x0b\x32\x13.magma.lte.oai.Ecgi\x12\x0c\n\x04trxn\x18\x05 \x01(\x0c\x12\x0e\n\x06imsi64\x18\x06 \x01(\x04\x12\x14\n\x0cmme_teid_s11\x18\x07 \x01(\r\x12\x1a\n\x12mme_ip_address_s11\x18\x08 \x01(\x0c\x12\x17\n\x0fsgw_teid_s11_s4\x18\t \x01(\r\x12\x1d\n\x15sgw_ip_address_s11_s4\x18\n \x01(\x0c\x12\x37\n\x0epdn_connection\x18\x0b \x01(\x0b\x32\x1f.magma.lte.oai.SgwPdnConnection\"T\n\x0cSgwUeContext\x12\x44\n\x12sgw_bearer_context\x18\x01 \x03(\x0b\x32(.magma.lte.oai.SgwS8EpsBearerContextInfo\"7\n\x08SgwState\x12\x16\n\x0elast_tunnel_id\x18\x01 \x01(\r\x12\x13\n\x0bgtpv1u_teid\x18\x02 \x01(\rB\x1fZ\x1dmagma/lte/cloud/go/protos/oaib\x06proto3'
  ,
  dependencies=[lte_dot_protos_dot_oai_dot_common__types__pb2.DESCRIPTOR,lte_dot_protos_dot_oai_dot_std__3gpp__types__pb2.DESCRIPTOR,lte_dot_protos_dot_oai_dot_spgw__state__pb2.DESCRIPTOR,])




_SGWS8EPSBEARERCONTEXTINFO = _descriptor.Descriptor(
  name='SgwS8EpsBearerContextInfo',
  full_name='magma.lte.oai.SgwS8EpsBearerContextInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='imsi', full_name='magma.lte.oai.SgwS8EpsBearerContextInfo.imsi', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imsi_unauth_indicator', full_name='magma.lte.oai.SgwS8EpsBearerContextInfo.imsi_unauth_indicator', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msisdn', full_name='magma.lte.oai.SgwS8EpsBearerContextInfo.msisdn', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_known_cell_id', full_name='magma.lte.oai.SgwS8EpsBearerContextInfo.last_known_cell_id', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trxn', full_name='magma.lte.oai.SgwS8EpsBearerContextInfo.trxn', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imsi64', full_name='magma.lte.oai.SgwS8EpsBearerContextInfo.imsi64', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mme_teid_s11', full_name='magma.lte.oai.SgwS8EpsBearerContextInfo.mme_teid_s11', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mme_ip_address_s11', full_name='magma.lte.oai.SgwS8EpsBearerContextInfo.mme_ip_address_s11', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sgw_teid_s11_s4', full_name='magma.lte.oai.SgwS8EpsBearerContextInfo.sgw_teid_s11_s4', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sgw_ip_address_s11_s4', full_name='magma.lte.oai.SgwS8EpsBearerContextInfo.sgw_ip_address_s11_s4', index=9,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pdn_connection', full_name='magma.lte.oai.SgwS8EpsBearerContextInfo.pdn_connection', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=485,
)


_SGWUECONTEXT = _descriptor.Descriptor(
  name='SgwUeContext',
  full_name='magma.lte.oai.SgwUeContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sgw_bearer_context', full_name='magma.lte.oai.SgwUeContext.sgw_bearer_context', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=487,
  serialized_end=571,
)


_SGWSTATE = _descriptor.Descriptor(
  name='SgwState',
  full_name='magma.lte.oai.SgwState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='last_tunnel_id', full_name='magma.lte.oai.SgwState.last_tunnel_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gtpv1u_teid', full_name='magma.lte.oai.SgwState.gtpv1u_teid', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=573,
  serialized_end=628,
)

_SGWS8EPSBEARERCONTEXTINFO.fields_by_name['last_known_cell_id'].message_type = lte_dot_protos_dot_oai_dot_common__types__pb2._ECGI
_SGWS8EPSBEARERCONTEXTINFO.fields_by_name['pdn_connection'].message_type = lte_dot_protos_dot_oai_dot_spgw__state__pb2._SGWPDNCONNECTION
_SGWUECONTEXT.fields_by_name['sgw_bearer_context'].message_type = _SGWS8EPSBEARERCONTEXTINFO
DESCRIPTOR.message_types_by_name['SgwS8EpsBearerContextInfo'] = _SGWS8EPSBEARERCONTEXTINFO
DESCRIPTOR.message_types_by_name['SgwUeContext'] = _SGWUECONTEXT
DESCRIPTOR.message_types_by_name['SgwState'] = _SGWSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SgwS8EpsBearerContextInfo = _reflection.GeneratedProtocolMessageType('SgwS8EpsBearerContextInfo', (_message.Message,), {
  'DESCRIPTOR' : _SGWS8EPSBEARERCONTEXTINFO,
  '__module__' : 'lte.protos.oai.sgw_state_pb2'
  # @@protoc_insertion_point(class_scope:magma.lte.oai.SgwS8EpsBearerContextInfo)
  })
_sym_db.RegisterMessage(SgwS8EpsBearerContextInfo)

SgwUeContext = _reflection.GeneratedProtocolMessageType('SgwUeContext', (_message.Message,), {
  'DESCRIPTOR' : _SGWUECONTEXT,
  '__module__' : 'lte.protos.oai.sgw_state_pb2'
  # @@protoc_insertion_point(class_scope:magma.lte.oai.SgwUeContext)
  })
_sym_db.RegisterMessage(SgwUeContext)

SgwState = _reflection.GeneratedProtocolMessageType('SgwState', (_message.Message,), {
  'DESCRIPTOR' : _SGWSTATE,
  '__module__' : 'lte.protos.oai.sgw_state_pb2'
  # @@protoc_insertion_point(class_scope:magma.lte.oai.SgwState)
  })
_sym_db.RegisterMessage(SgwState)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
