# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lte/protos/keyval.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from lte.protos import subscriberdb_pb2 as lte_dot_protos_dot_subscriberdb__pb2
from lte.protos import mobilityd_pb2 as lte_dot_protos_dot_mobilityd__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='lte/protos/keyval.proto',
  package='magma.lte',
  syntax='proto3',
  serialized_options=b'Z\031magma/lte/cloud/go/protos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17lte/protos/keyval.proto\x12\tmagma.lte\x1a\x1dlte/protos/subscriberdb.proto\x1a\x1alte/protos/mobilityd.proto\"=\n\x10\x41ssignedIPBlocks\x12)\n\rip_block_list\x18\x01 \x03(\x0b\x32\x12.magma.lte.IPBlock\"\xd2\x02\n\x06IPDesc\x12 \n\x02ip\x18\x01 \x01(\x0b\x32\x14.magma.lte.IPAddress\x12$\n\x08ip_block\x18\x02 \x01(\x0b\x32\x12.magma.lte.IPBlock\x12(\n\x05state\x18\x03 \x01(\x0e\x32\x19.magma.lte.IPDesc.IPState\x12$\n\x03sid\x18\x04 \x01(\x0b\x32\x17.magma.lte.SubscriberID\x12&\n\x04type\x18\x05 \x01(\x0e\x32\x18.magma.lte.IPDesc.IPType\x12\x0f\n\x07vlan_id\x18\x06 \x01(\r\"J\n\x07IPState\x12\x08\n\x04\x46REE\x10\x00\x12\r\n\tALLOCATED\x10\x01\x12\x0c\n\x08RELEASED\x10\x02\x12\n\n\x06REAPED\x10\x03\x12\x0c\n\x08RESERVED\x10\x04\"+\n\x06IPType\x12\n\n\x06STATIC\x10\x00\x12\x0b\n\x07IP_POOL\x10\x01\x12\x08\n\x04\x44HCP\x10\x03\".\n\x07IPDescs\x12#\n\x08ip_descs\x18\x01 \x03(\x0b\x32\x11.magma.lte.IPDescB\x1bZ\x19magma/lte/cloud/go/protosb\x06proto3'
  ,
  dependencies=[lte_dot_protos_dot_subscriberdb__pb2.DESCRIPTOR,lte_dot_protos_dot_mobilityd__pb2.DESCRIPTOR,])



_IPDESC_IPSTATE = _descriptor.EnumDescriptor(
  name='IPState',
  full_name='magma.lte.IPDesc.IPState',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FREE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ALLOCATED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RELEASED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REAPED', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESERVED', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=380,
  serialized_end=454,
)
_sym_db.RegisterEnumDescriptor(_IPDESC_IPSTATE)

_IPDESC_IPTYPE = _descriptor.EnumDescriptor(
  name='IPType',
  full_name='magma.lte.IPDesc.IPType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STATIC', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='IP_POOL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DHCP', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=456,
  serialized_end=499,
)
_sym_db.RegisterEnumDescriptor(_IPDESC_IPTYPE)


_ASSIGNEDIPBLOCKS = _descriptor.Descriptor(
  name='AssignedIPBlocks',
  full_name='magma.lte.AssignedIPBlocks',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip_block_list', full_name='magma.lte.AssignedIPBlocks.ip_block_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=158,
)


_IPDESC = _descriptor.Descriptor(
  name='IPDesc',
  full_name='magma.lte.IPDesc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='magma.lte.IPDesc.ip', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ip_block', full_name='magma.lte.IPDesc.ip_block', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='magma.lte.IPDesc.state', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sid', full_name='magma.lte.IPDesc.sid', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='magma.lte.IPDesc.type', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vlan_id', full_name='magma.lte.IPDesc.vlan_id', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _IPDESC_IPSTATE,
    _IPDESC_IPTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=499,
)


_IPDESCS = _descriptor.Descriptor(
  name='IPDescs',
  full_name='magma.lte.IPDescs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip_descs', full_name='magma.lte.IPDescs.ip_descs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=501,
  serialized_end=547,
)

_ASSIGNEDIPBLOCKS.fields_by_name['ip_block_list'].message_type = lte_dot_protos_dot_mobilityd__pb2._IPBLOCK
_IPDESC.fields_by_name['ip'].message_type = lte_dot_protos_dot_mobilityd__pb2._IPADDRESS
_IPDESC.fields_by_name['ip_block'].message_type = lte_dot_protos_dot_mobilityd__pb2._IPBLOCK
_IPDESC.fields_by_name['state'].enum_type = _IPDESC_IPSTATE
_IPDESC.fields_by_name['sid'].message_type = lte_dot_protos_dot_subscriberdb__pb2._SUBSCRIBERID
_IPDESC.fields_by_name['type'].enum_type = _IPDESC_IPTYPE
_IPDESC_IPSTATE.containing_type = _IPDESC
_IPDESC_IPTYPE.containing_type = _IPDESC
_IPDESCS.fields_by_name['ip_descs'].message_type = _IPDESC
DESCRIPTOR.message_types_by_name['AssignedIPBlocks'] = _ASSIGNEDIPBLOCKS
DESCRIPTOR.message_types_by_name['IPDesc'] = _IPDESC
DESCRIPTOR.message_types_by_name['IPDescs'] = _IPDESCS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AssignedIPBlocks = _reflection.GeneratedProtocolMessageType('AssignedIPBlocks', (_message.Message,), {
  'DESCRIPTOR' : _ASSIGNEDIPBLOCKS,
  '__module__' : 'lte.protos.keyval_pb2'
  # @@protoc_insertion_point(class_scope:magma.lte.AssignedIPBlocks)
  })
_sym_db.RegisterMessage(AssignedIPBlocks)

IPDesc = _reflection.GeneratedProtocolMessageType('IPDesc', (_message.Message,), {
  'DESCRIPTOR' : _IPDESC,
  '__module__' : 'lte.protos.keyval_pb2'
  # @@protoc_insertion_point(class_scope:magma.lte.IPDesc)
  })
_sym_db.RegisterMessage(IPDesc)

IPDescs = _reflection.GeneratedProtocolMessageType('IPDescs', (_message.Message,), {
  'DESCRIPTOR' : _IPDESCS,
  '__module__' : 'lte.protos.keyval_pb2'
  # @@protoc_insertion_point(class_scope:magma.lte.IPDescs)
  })
_sym_db.RegisterMessage(IPDescs)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
