# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lte/protos/s1ap_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from orc8r.protos import common_pb2 as orc8r_dot_protos_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='lte/protos/s1ap_service.proto',
  package='magma.lte',
  syntax='proto3',
  serialized_options=b'Z\031magma/lte/cloud/go/protos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1dlte/protos/s1ap_service.proto\x12\tmagma.lte\x1a\x19orc8r/protos/common.proto\"\x87\x01\n\x0e\x45nbStateResult\x12\x41\n\renb_state_map\x18\x01 \x03(\x0b\x32*.magma.lte.EnbStateResult.EnbStateMapEntry\x1a\x32\n\x10\x45nbStateMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x32L\n\x0bS1apService\x12=\n\x0bGetENBState\x12\x11.magma.orc8r.Void\x1a\x19.magma.lte.EnbStateResult\"\x00\x42\x1bZ\x19magma/lte/cloud/go/protosb\x06proto3'
  ,
  dependencies=[orc8r_dot_protos_dot_common__pb2.DESCRIPTOR,])




_ENBSTATERESULT_ENBSTATEMAPENTRY = _descriptor.Descriptor(
  name='EnbStateMapEntry',
  full_name='magma.lte.EnbStateResult.EnbStateMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='magma.lte.EnbStateResult.EnbStateMapEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='magma.lte.EnbStateResult.EnbStateMapEntry.value', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=207,
)

_ENBSTATERESULT = _descriptor.Descriptor(
  name='EnbStateResult',
  full_name='magma.lte.EnbStateResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='enb_state_map', full_name='magma.lte.EnbStateResult.enb_state_map', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_ENBSTATERESULT_ENBSTATEMAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=207,
)

_ENBSTATERESULT_ENBSTATEMAPENTRY.containing_type = _ENBSTATERESULT
_ENBSTATERESULT.fields_by_name['enb_state_map'].message_type = _ENBSTATERESULT_ENBSTATEMAPENTRY
DESCRIPTOR.message_types_by_name['EnbStateResult'] = _ENBSTATERESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EnbStateResult = _reflection.GeneratedProtocolMessageType('EnbStateResult', (_message.Message,), {

  'EnbStateMapEntry' : _reflection.GeneratedProtocolMessageType('EnbStateMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _ENBSTATERESULT_ENBSTATEMAPENTRY,
    '__module__' : 'lte.protos.s1ap_service_pb2'
    # @@protoc_insertion_point(class_scope:magma.lte.EnbStateResult.EnbStateMapEntry)
    })
  ,
  'DESCRIPTOR' : _ENBSTATERESULT,
  '__module__' : 'lte.protos.s1ap_service_pb2'
  # @@protoc_insertion_point(class_scope:magma.lte.EnbStateResult)
  })
_sym_db.RegisterMessage(EnbStateResult)
_sym_db.RegisterMessage(EnbStateResult.EnbStateMapEntry)


DESCRIPTOR._options = None
_ENBSTATERESULT_ENBSTATEMAPENTRY._options = None

_S1APSERVICE = _descriptor.ServiceDescriptor(
  name='S1apService',
  full_name='magma.lte.S1apService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=209,
  serialized_end=285,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetENBState',
    full_name='magma.lte.S1apService.GetENBState',
    index=0,
    containing_service=None,
    input_type=orc8r_dot_protos_dot_common__pb2._VOID,
    output_type=_ENBSTATERESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_S1APSERVICE)

DESCRIPTOR.services_by_name['S1apService'] = _S1APSERVICE

# @@protoc_insertion_point(module_scope)
