# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lte/protos/s6a_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lte/protos/s6a_service.proto',
  package='magma.lte',
  syntax='proto3',
  serialized_options=b'Z\031magma/lte/cloud/go/protos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1clte/protos/s6a_service.proto\x12\tmagma.lte\"\x1a\n\x18\x44\x65leteSubscriberResponse\",\n\x17\x44\x65leteSubscriberRequest\x12\x11\n\timsi_list\x18\x01 \x03(\t2k\n\nS6aService\x12]\n\x10\x44\x65leteSubscriber\x12\".magma.lte.DeleteSubscriberRequest\x1a#.magma.lte.DeleteSubscriberResponse\"\x00\x42\x1bZ\x19magma/lte/cloud/go/protosb\x06proto3'
)




_DELETESUBSCRIBERRESPONSE = _descriptor.Descriptor(
  name='DeleteSubscriberResponse',
  full_name='magma.lte.DeleteSubscriberResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=69,
)


_DELETESUBSCRIBERREQUEST = _descriptor.Descriptor(
  name='DeleteSubscriberRequest',
  full_name='magma.lte.DeleteSubscriberRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='imsi_list', full_name='magma.lte.DeleteSubscriberRequest.imsi_list', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=115,
)

DESCRIPTOR.message_types_by_name['DeleteSubscriberResponse'] = _DELETESUBSCRIBERRESPONSE
DESCRIPTOR.message_types_by_name['DeleteSubscriberRequest'] = _DELETESUBSCRIBERREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DeleteSubscriberResponse = _reflection.GeneratedProtocolMessageType('DeleteSubscriberResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETESUBSCRIBERRESPONSE,
  '__module__' : 'lte.protos.s6a_service_pb2'
  # @@protoc_insertion_point(class_scope:magma.lte.DeleteSubscriberResponse)
  })
_sym_db.RegisterMessage(DeleteSubscriberResponse)

DeleteSubscriberRequest = _reflection.GeneratedProtocolMessageType('DeleteSubscriberRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETESUBSCRIBERREQUEST,
  '__module__' : 'lte.protos.s6a_service_pb2'
  # @@protoc_insertion_point(class_scope:magma.lte.DeleteSubscriberRequest)
  })
_sym_db.RegisterMessage(DeleteSubscriberRequest)


DESCRIPTOR._options = None

_S6ASERVICE = _descriptor.ServiceDescriptor(
  name='S6aService',
  full_name='magma.lte.S6aService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=117,
  serialized_end=224,
  methods=[
  _descriptor.MethodDescriptor(
    name='DeleteSubscriber',
    full_name='magma.lte.S6aService.DeleteSubscriber',
    index=0,
    containing_service=None,
    input_type=_DELETESUBSCRIBERREQUEST,
    output_type=_DELETESUBSCRIBERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_S6ASERVICE)

DESCRIPTOR.services_by_name['S6aService'] = _S6ASERVICE

# @@protoc_insertion_point(module_scope)
