# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from lte.protos import spgw_service_pb2 as lte_dot_protos_dot_spgw__service__pb2


class SpgwServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateBearer = channel.unary_unary(
                '/magma.lte.SpgwService/CreateBearer',
                request_serializer=lte_dot_protos_dot_spgw__service__pb2.CreateBearerRequest.SerializeToString,
                response_deserializer=lte_dot_protos_dot_spgw__service__pb2.CreateBearerResult.FromString,
                )
        self.DeleteBearer = channel.unary_unary(
                '/magma.lte.SpgwService/DeleteBearer',
                request_serializer=lte_dot_protos_dot_spgw__service__pb2.DeleteBearerRequest.SerializeToString,
                response_deserializer=lte_dot_protos_dot_spgw__service__pb2.DeleteBearerResult.FromString,
                )


class SpgwServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateBearer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBearer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpgwServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateBearer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBearer,
                    request_deserializer=lte_dot_protos_dot_spgw__service__pb2.CreateBearerRequest.FromString,
                    response_serializer=lte_dot_protos_dot_spgw__service__pb2.CreateBearerResult.SerializeToString,
            ),
            'DeleteBearer': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBearer,
                    request_deserializer=lte_dot_protos_dot_spgw__service__pb2.DeleteBearerRequest.FromString,
                    response_serializer=lte_dot_protos_dot_spgw__service__pb2.DeleteBearerResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'magma.lte.SpgwService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SpgwService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateBearer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/magma.lte.SpgwService/CreateBearer',
            lte_dot_protos_dot_spgw__service__pb2.CreateBearerRequest.SerializeToString,
            lte_dot_protos_dot_spgw__service__pb2.CreateBearerResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteBearer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/magma.lte.SpgwService/DeleteBearer',
            lte_dot_protos_dot_spgw__service__pb2.DeleteBearerRequest.SerializeToString,
            lte_dot_protos_dot_spgw__service__pb2.DeleteBearerResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
