# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orc8r/protos/bootstrapper.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from orc8r.protos import certifier_pb2 as orc8r_dot_protos_dot_certifier__pb2
from orc8r.protos import identity_pb2 as orc8r_dot_protos_dot_identity__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='orc8r/protos/bootstrapper.proto',
  package='magma.orc8r',
  syntax='proto3',
  serialized_options=b'Z\031magma/orc8r/lib/go/protos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1forc8r/protos/bootstrapper.proto\x12\x0bmagma.orc8r\x1a\x1corc8r/protos/certifier.proto\x1a\x1borc8r/protos/identity.proto\"S\n\tChallenge\x12\x33\n\x08key_type\x18\x01 \x01(\x0e\x32!.magma.orc8r.ChallengeKey.KeyType\x12\x11\n\tchallenge\x18\x02 \x01(\x0c\"\x99\x01\n\x0c\x43hallengeKey\x12\x33\n\x08key_type\x18\x01 \x01(\x0e\x32!.magma.orc8r.ChallengeKey.KeyType\x12\x0b\n\x03key\x18\x02 \x01(\x0c\"G\n\x07KeyType\x12\x08\n\x04\x45\x43HO\x10\x00\x12\x17\n\x13SOFTWARE_RSA_SHA256\x10\x01\x12\x19\n\x15SOFTWARE_ECDSA_SHA256\x10\x02\"\xe7\x02\n\x08Response\x12+\n\x05hw_id\x18\x01 \x01(\x0b\x32\x1c.magma.orc8r.AccessGatewayID\x12\x11\n\tchallenge\x18\x02 \x01(\x0c\x12\x33\n\recho_response\x18\x03 \x01(\x0b\x32\x1a.magma.orc8r.Response.EchoH\x00\x12\x31\n\x0crsa_response\x18\x04 \x01(\x0b\x32\x19.magma.orc8r.Response.RSAH\x00\x12\x35\n\x0e\x65\x63\x64sa_response\x18\x05 \x01(\x0b\x32\x1b.magma.orc8r.Response.ECDSAH\x00\x12\x1d\n\x03\x63sr\x18\x06 \x01(\x0b\x32\x10.magma.orc8r.CSR\x1a\x18\n\x04\x45\x63ho\x12\x10\n\x08response\x18\x01 \x01(\x0c\x1a\x18\n\x03RSA\x12\x11\n\tsignature\x18\x01 \x01(\x0c\x1a\x1d\n\x05\x45\x43\x44SA\x12\t\n\x01r\x18\x01 \x01(\x0c\x12\t\n\x01s\x18\x02 \x01(\x0c\x42\n\n\x08response2\x98\x01\n\x0c\x42ootstrapper\x12\x46\n\x0cGetChallenge\x12\x1c.magma.orc8r.AccessGatewayID\x1a\x16.magma.orc8r.Challenge\"\x00\x12@\n\x0bRequestSign\x12\x15.magma.orc8r.Response\x1a\x18.magma.orc8r.Certificate\"\x00\x42\x1bZ\x19magma/orc8r/lib/go/protosb\x06proto3'
  ,
  dependencies=[orc8r_dot_protos_dot_certifier__pb2.DESCRIPTOR,orc8r_dot_protos_dot_identity__pb2.DESCRIPTOR,])



_CHALLENGEKEY_KEYTYPE = _descriptor.EnumDescriptor(
  name='KeyType',
  full_name='magma.orc8r.ChallengeKey.KeyType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ECHO', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SOFTWARE_RSA_SHA256', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SOFTWARE_ECDSA_SHA256', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=275,
  serialized_end=346,
)
_sym_db.RegisterEnumDescriptor(_CHALLENGEKEY_KEYTYPE)


_CHALLENGE = _descriptor.Descriptor(
  name='Challenge',
  full_name='magma.orc8r.Challenge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key_type', full_name='magma.orc8r.Challenge.key_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='challenge', full_name='magma.orc8r.Challenge.challenge', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=190,
)


_CHALLENGEKEY = _descriptor.Descriptor(
  name='ChallengeKey',
  full_name='magma.orc8r.ChallengeKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key_type', full_name='magma.orc8r.ChallengeKey.key_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='magma.orc8r.ChallengeKey.key', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CHALLENGEKEY_KEYTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=346,
)


_RESPONSE_ECHO = _descriptor.Descriptor(
  name='Echo',
  full_name='magma.orc8r.Response.Echo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='magma.orc8r.Response.Echo.response', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=615,
  serialized_end=639,
)

_RESPONSE_RSA = _descriptor.Descriptor(
  name='RSA',
  full_name='magma.orc8r.Response.RSA',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='signature', full_name='magma.orc8r.Response.RSA.signature', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=641,
  serialized_end=665,
)

_RESPONSE_ECDSA = _descriptor.Descriptor(
  name='ECDSA',
  full_name='magma.orc8r.Response.ECDSA',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='r', full_name='magma.orc8r.Response.ECDSA.r', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='s', full_name='magma.orc8r.Response.ECDSA.s', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=667,
  serialized_end=696,
)

_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='magma.orc8r.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hw_id', full_name='magma.orc8r.Response.hw_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='challenge', full_name='magma.orc8r.Response.challenge', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='echo_response', full_name='magma.orc8r.Response.echo_response', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rsa_response', full_name='magma.orc8r.Response.rsa_response', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ecdsa_response', full_name='magma.orc8r.Response.ecdsa_response', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='csr', full_name='magma.orc8r.Response.csr', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_RESPONSE_ECHO, _RESPONSE_RSA, _RESPONSE_ECDSA, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='response', full_name='magma.orc8r.Response.response',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=349,
  serialized_end=708,
)

_CHALLENGE.fields_by_name['key_type'].enum_type = _CHALLENGEKEY_KEYTYPE
_CHALLENGEKEY.fields_by_name['key_type'].enum_type = _CHALLENGEKEY_KEYTYPE
_CHALLENGEKEY_KEYTYPE.containing_type = _CHALLENGEKEY
_RESPONSE_ECHO.containing_type = _RESPONSE
_RESPONSE_RSA.containing_type = _RESPONSE
_RESPONSE_ECDSA.containing_type = _RESPONSE
_RESPONSE.fields_by_name['hw_id'].message_type = orc8r_dot_protos_dot_identity__pb2._ACCESSGATEWAYID
_RESPONSE.fields_by_name['echo_response'].message_type = _RESPONSE_ECHO
_RESPONSE.fields_by_name['rsa_response'].message_type = _RESPONSE_RSA
_RESPONSE.fields_by_name['ecdsa_response'].message_type = _RESPONSE_ECDSA
_RESPONSE.fields_by_name['csr'].message_type = orc8r_dot_protos_dot_certifier__pb2._CSR
_RESPONSE.oneofs_by_name['response'].fields.append(
  _RESPONSE.fields_by_name['echo_response'])
_RESPONSE.fields_by_name['echo_response'].containing_oneof = _RESPONSE.oneofs_by_name['response']
_RESPONSE.oneofs_by_name['response'].fields.append(
  _RESPONSE.fields_by_name['rsa_response'])
_RESPONSE.fields_by_name['rsa_response'].containing_oneof = _RESPONSE.oneofs_by_name['response']
_RESPONSE.oneofs_by_name['response'].fields.append(
  _RESPONSE.fields_by_name['ecdsa_response'])
_RESPONSE.fields_by_name['ecdsa_response'].containing_oneof = _RESPONSE.oneofs_by_name['response']
DESCRIPTOR.message_types_by_name['Challenge'] = _CHALLENGE
DESCRIPTOR.message_types_by_name['ChallengeKey'] = _CHALLENGEKEY
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Challenge = _reflection.GeneratedProtocolMessageType('Challenge', (_message.Message,), {
  'DESCRIPTOR' : _CHALLENGE,
  '__module__' : 'orc8r.protos.bootstrapper_pb2'
  # @@protoc_insertion_point(class_scope:magma.orc8r.Challenge)
  })
_sym_db.RegisterMessage(Challenge)

ChallengeKey = _reflection.GeneratedProtocolMessageType('ChallengeKey', (_message.Message,), {
  'DESCRIPTOR' : _CHALLENGEKEY,
  '__module__' : 'orc8r.protos.bootstrapper_pb2'
  # @@protoc_insertion_point(class_scope:magma.orc8r.ChallengeKey)
  })
_sym_db.RegisterMessage(ChallengeKey)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {

  'Echo' : _reflection.GeneratedProtocolMessageType('Echo', (_message.Message,), {
    'DESCRIPTOR' : _RESPONSE_ECHO,
    '__module__' : 'orc8r.protos.bootstrapper_pb2'
    # @@protoc_insertion_point(class_scope:magma.orc8r.Response.Echo)
    })
  ,

  'RSA' : _reflection.GeneratedProtocolMessageType('RSA', (_message.Message,), {
    'DESCRIPTOR' : _RESPONSE_RSA,
    '__module__' : 'orc8r.protos.bootstrapper_pb2'
    # @@protoc_insertion_point(class_scope:magma.orc8r.Response.RSA)
    })
  ,

  'ECDSA' : _reflection.GeneratedProtocolMessageType('ECDSA', (_message.Message,), {
    'DESCRIPTOR' : _RESPONSE_ECDSA,
    '__module__' : 'orc8r.protos.bootstrapper_pb2'
    # @@protoc_insertion_point(class_scope:magma.orc8r.Response.ECDSA)
    })
  ,
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'orc8r.protos.bootstrapper_pb2'
  # @@protoc_insertion_point(class_scope:magma.orc8r.Response)
  })
_sym_db.RegisterMessage(Response)
_sym_db.RegisterMessage(Response.Echo)
_sym_db.RegisterMessage(Response.RSA)
_sym_db.RegisterMessage(Response.ECDSA)


DESCRIPTOR._options = None

_BOOTSTRAPPER = _descriptor.ServiceDescriptor(
  name='Bootstrapper',
  full_name='magma.orc8r.Bootstrapper',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=711,
  serialized_end=863,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetChallenge',
    full_name='magma.orc8r.Bootstrapper.GetChallenge',
    index=0,
    containing_service=None,
    input_type=orc8r_dot_protos_dot_identity__pb2._ACCESSGATEWAYID,
    output_type=_CHALLENGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RequestSign',
    full_name='magma.orc8r.Bootstrapper.RequestSign',
    index=1,
    containing_service=None,
    input_type=_RESPONSE,
    output_type=orc8r_dot_protos_dot_certifier__pb2._CERTIFICATE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BOOTSTRAPPER)

DESCRIPTOR.services_by_name['Bootstrapper'] = _BOOTSTRAPPER

# @@protoc_insertion_point(module_scope)
