# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orc8r/protos/digest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='orc8r/protos/digest.proto',
  package='magma.orc8r',
  syntax='proto3',
  serialized_options=b'Z\031magma/orc8r/lib/go/protos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19orc8r/protos/digest.proto\x12\x0bmagma.orc8r\x1a\x19google/protobuf/any.proto\"e\n\nDigestTree\x12(\n\x0broot_digest\x18\x01 \x01(\x0b\x32\x13.magma.orc8r.Digest\x12-\n\x0cleaf_digests\x18\x02 \x03(\x0b\x32\x17.magma.orc8r.LeafDigest\"#\n\x06\x44igest\x12\x19\n\x11md5_base64_digest\x18\x01 \x01(\t\"=\n\nLeafDigest\x12\n\n\x02id\x18\x01 \x01(\t\x12#\n\x06\x64igest\x18\x02 \x01(\x0b\x32\x13.magma.orc8r.Digest\"7\n\x0bLeafDigests\x12(\n\x07\x64igests\x18\x01 \x03(\x0b\x32\x17.magma.orc8r.LeafDigest\"D\n\tChangeset\x12&\n\x08to_renew\x18\x01 \x03(\x0b\x32\x14.google.protobuf.Any\x12\x0f\n\x07\x64\x65leted\x18\x02 \x03(\tB\x1bZ\x19magma/orc8r/lib/go/protosb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_DIGESTTREE = _descriptor.Descriptor(
  name='DigestTree',
  full_name='magma.orc8r.DigestTree',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='root_digest', full_name='magma.orc8r.DigestTree.root_digest', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='leaf_digests', full_name='magma.orc8r.DigestTree.leaf_digests', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=170,
)


_DIGEST = _descriptor.Descriptor(
  name='Digest',
  full_name='magma.orc8r.Digest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='md5_base64_digest', full_name='magma.orc8r.Digest.md5_base64_digest', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=207,
)


_LEAFDIGEST = _descriptor.Descriptor(
  name='LeafDigest',
  full_name='magma.orc8r.LeafDigest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='magma.orc8r.LeafDigest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='digest', full_name='magma.orc8r.LeafDigest.digest', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=270,
)


_LEAFDIGESTS = _descriptor.Descriptor(
  name='LeafDigests',
  full_name='magma.orc8r.LeafDigests',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='digests', full_name='magma.orc8r.LeafDigests.digests', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=327,
)


_CHANGESET = _descriptor.Descriptor(
  name='Changeset',
  full_name='magma.orc8r.Changeset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='to_renew', full_name='magma.orc8r.Changeset.to_renew', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deleted', full_name='magma.orc8r.Changeset.deleted', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=329,
  serialized_end=397,
)

_DIGESTTREE.fields_by_name['root_digest'].message_type = _DIGEST
_DIGESTTREE.fields_by_name['leaf_digests'].message_type = _LEAFDIGEST
_LEAFDIGEST.fields_by_name['digest'].message_type = _DIGEST
_LEAFDIGESTS.fields_by_name['digests'].message_type = _LEAFDIGEST
_CHANGESET.fields_by_name['to_renew'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['DigestTree'] = _DIGESTTREE
DESCRIPTOR.message_types_by_name['Digest'] = _DIGEST
DESCRIPTOR.message_types_by_name['LeafDigest'] = _LEAFDIGEST
DESCRIPTOR.message_types_by_name['LeafDigests'] = _LEAFDIGESTS
DESCRIPTOR.message_types_by_name['Changeset'] = _CHANGESET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DigestTree = _reflection.GeneratedProtocolMessageType('DigestTree', (_message.Message,), {
  'DESCRIPTOR' : _DIGESTTREE,
  '__module__' : 'orc8r.protos.digest_pb2'
  # @@protoc_insertion_point(class_scope:magma.orc8r.DigestTree)
  })
_sym_db.RegisterMessage(DigestTree)

Digest = _reflection.GeneratedProtocolMessageType('Digest', (_message.Message,), {
  'DESCRIPTOR' : _DIGEST,
  '__module__' : 'orc8r.protos.digest_pb2'
  # @@protoc_insertion_point(class_scope:magma.orc8r.Digest)
  })
_sym_db.RegisterMessage(Digest)

LeafDigest = _reflection.GeneratedProtocolMessageType('LeafDigest', (_message.Message,), {
  'DESCRIPTOR' : _LEAFDIGEST,
  '__module__' : 'orc8r.protos.digest_pb2'
  # @@protoc_insertion_point(class_scope:magma.orc8r.LeafDigest)
  })
_sym_db.RegisterMessage(LeafDigest)

LeafDigests = _reflection.GeneratedProtocolMessageType('LeafDigests', (_message.Message,), {
  'DESCRIPTOR' : _LEAFDIGESTS,
  '__module__' : 'orc8r.protos.digest_pb2'
  # @@protoc_insertion_point(class_scope:magma.orc8r.LeafDigests)
  })
_sym_db.RegisterMessage(LeafDigests)

Changeset = _reflection.GeneratedProtocolMessageType('Changeset', (_message.Message,), {
  'DESCRIPTOR' : _CHANGESET,
  '__module__' : 'orc8r.protos.digest_pb2'
  # @@protoc_insertion_point(class_scope:magma.orc8r.Changeset)
  })
_sym_db.RegisterMessage(Changeset)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
