# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orc8r/protos/identity.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='orc8r/protos/identity.proto',
  package='magma.orc8r',
  syntax='proto3',
  serialized_options=b'Z\031magma/orc8r/lib/go/protos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1borc8r/protos/identity.proto\x12\x0bmagma.orc8r\"\x84\x03\n\x08Identity\x12\x30\n\x07gateway\x18\x01 \x01(\x0b\x32\x1d.magma.orc8r.Identity.GatewayH\x00\x12\x12\n\x08operator\x18\x02 \x01(\tH\x00\x12\x11\n\x07network\x18\x03 \x01(\tH\x00\x12\x32\n\x08wildcard\x18\x0b \x01(\x0b\x32\x1e.magma.orc8r.Identity.WildcardH\x00\x1am\n\x08Wildcard\x12\x31\n\x04type\x18\x01 \x01(\x0e\x32#.magma.orc8r.Identity.Wildcard.Type\".\n\x04Type\x12\x0b\n\x07Gateway\x10\x00\x12\x0c\n\x08Operator\x10\x01\x12\x0b\n\x07Network\x10\x02\x1a\x46\n\x07Gateway\x12\x13\n\x0bhardware_id\x18\x01 \x01(\t\x12\x12\n\nnetwork_id\x18\x02 \x01(\t\x12\x12\n\nlogical_id\x18\x03 \x01(\t\x1a+\n\x04List\x12#\n\x04list\x18\x01 \x03(\x0b\x32\x15.magma.orc8r.IdentityB\x07\n\x05Value\"\x1d\n\x0f\x41\x63\x63\x65ssGatewayID\x12\n\n\x02id\x18\x01 \x01(\tB\x1bZ\x19magma/orc8r/lib/go/protosb\x06proto3'
)



_IDENTITY_WILDCARD_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='magma.orc8r.Identity.Wildcard.Type',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Gateway', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Operator', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Network', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=261,
  serialized_end=307,
)
_sym_db.RegisterEnumDescriptor(_IDENTITY_WILDCARD_TYPE)


_IDENTITY_WILDCARD = _descriptor.Descriptor(
  name='Wildcard',
  full_name='magma.orc8r.Identity.Wildcard',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='magma.orc8r.Identity.Wildcard.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _IDENTITY_WILDCARD_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=307,
)

_IDENTITY_GATEWAY = _descriptor.Descriptor(
  name='Gateway',
  full_name='magma.orc8r.Identity.Gateway',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hardware_id', full_name='magma.orc8r.Identity.Gateway.hardware_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='network_id', full_name='magma.orc8r.Identity.Gateway.network_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='logical_id', full_name='magma.orc8r.Identity.Gateway.logical_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=379,
)

_IDENTITY_LIST = _descriptor.Descriptor(
  name='List',
  full_name='magma.orc8r.Identity.List',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='list', full_name='magma.orc8r.Identity.List.list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=381,
  serialized_end=424,
)

_IDENTITY = _descriptor.Descriptor(
  name='Identity',
  full_name='magma.orc8r.Identity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gateway', full_name='magma.orc8r.Identity.gateway', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operator', full_name='magma.orc8r.Identity.operator', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='network', full_name='magma.orc8r.Identity.network', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wildcard', full_name='magma.orc8r.Identity.wildcard', index=3,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_IDENTITY_WILDCARD, _IDENTITY_GATEWAY, _IDENTITY_LIST, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Value', full_name='magma.orc8r.Identity.Value',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=45,
  serialized_end=433,
)


_ACCESSGATEWAYID = _descriptor.Descriptor(
  name='AccessGatewayID',
  full_name='magma.orc8r.AccessGatewayID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='magma.orc8r.AccessGatewayID.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=435,
  serialized_end=464,
)

_IDENTITY_WILDCARD.fields_by_name['type'].enum_type = _IDENTITY_WILDCARD_TYPE
_IDENTITY_WILDCARD.containing_type = _IDENTITY
_IDENTITY_WILDCARD_TYPE.containing_type = _IDENTITY_WILDCARD
_IDENTITY_GATEWAY.containing_type = _IDENTITY
_IDENTITY_LIST.fields_by_name['list'].message_type = _IDENTITY
_IDENTITY_LIST.containing_type = _IDENTITY
_IDENTITY.fields_by_name['gateway'].message_type = _IDENTITY_GATEWAY
_IDENTITY.fields_by_name['wildcard'].message_type = _IDENTITY_WILDCARD
_IDENTITY.oneofs_by_name['Value'].fields.append(
  _IDENTITY.fields_by_name['gateway'])
_IDENTITY.fields_by_name['gateway'].containing_oneof = _IDENTITY.oneofs_by_name['Value']
_IDENTITY.oneofs_by_name['Value'].fields.append(
  _IDENTITY.fields_by_name['operator'])
_IDENTITY.fields_by_name['operator'].containing_oneof = _IDENTITY.oneofs_by_name['Value']
_IDENTITY.oneofs_by_name['Value'].fields.append(
  _IDENTITY.fields_by_name['network'])
_IDENTITY.fields_by_name['network'].containing_oneof = _IDENTITY.oneofs_by_name['Value']
_IDENTITY.oneofs_by_name['Value'].fields.append(
  _IDENTITY.fields_by_name['wildcard'])
_IDENTITY.fields_by_name['wildcard'].containing_oneof = _IDENTITY.oneofs_by_name['Value']
DESCRIPTOR.message_types_by_name['Identity'] = _IDENTITY
DESCRIPTOR.message_types_by_name['AccessGatewayID'] = _ACCESSGATEWAYID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Identity = _reflection.GeneratedProtocolMessageType('Identity', (_message.Message,), {

  'Wildcard' : _reflection.GeneratedProtocolMessageType('Wildcard', (_message.Message,), {
    'DESCRIPTOR' : _IDENTITY_WILDCARD,
    '__module__' : 'orc8r.protos.identity_pb2'
    # @@protoc_insertion_point(class_scope:magma.orc8r.Identity.Wildcard)
    })
  ,

  'Gateway' : _reflection.GeneratedProtocolMessageType('Gateway', (_message.Message,), {
    'DESCRIPTOR' : _IDENTITY_GATEWAY,
    '__module__' : 'orc8r.protos.identity_pb2'
    # @@protoc_insertion_point(class_scope:magma.orc8r.Identity.Gateway)
    })
  ,

  'List' : _reflection.GeneratedProtocolMessageType('List', (_message.Message,), {
    'DESCRIPTOR' : _IDENTITY_LIST,
    '__module__' : 'orc8r.protos.identity_pb2'
    # @@protoc_insertion_point(class_scope:magma.orc8r.Identity.List)
    })
  ,
  'DESCRIPTOR' : _IDENTITY,
  '__module__' : 'orc8r.protos.identity_pb2'
  # @@protoc_insertion_point(class_scope:magma.orc8r.Identity)
  })
_sym_db.RegisterMessage(Identity)
_sym_db.RegisterMessage(Identity.Wildcard)
_sym_db.RegisterMessage(Identity.Gateway)
_sym_db.RegisterMessage(Identity.List)

AccessGatewayID = _reflection.GeneratedProtocolMessageType('AccessGatewayID', (_message.Message,), {
  'DESCRIPTOR' : _ACCESSGATEWAYID,
  '__module__' : 'orc8r.protos.identity_pb2'
  # @@protoc_insertion_point(class_scope:magma.orc8r.AccessGatewayID)
  })
_sym_db.RegisterMessage(AccessGatewayID)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
