# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orc8r/protos/redis.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='orc8r/protos/redis.proto',
  package='magma.orc8r',
  syntax='proto3',
  serialized_options=b'Z\031magma/orc8r/lib/go/protos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18orc8r/protos/redis.proto\x12\x0bmagma.orc8r\"I\n\nRedisState\x12\x16\n\x0eserialized_msg\x18\x01 \x01(\x0c\x12\x0f\n\x07version\x18\x02 \x01(\x04\x12\x12\n\nis_garbage\x18\x03 \x01(\x08\x42\x1bZ\x19magma/orc8r/lib/go/protosb\x06proto3'
)




_REDISSTATE = _descriptor.Descriptor(
  name='RedisState',
  full_name='magma.orc8r.RedisState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='serialized_msg', full_name='magma.orc8r.RedisState.serialized_msg', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='magma.orc8r.RedisState.version', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_garbage', full_name='magma.orc8r.RedisState.is_garbage', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=114,
)

DESCRIPTOR.message_types_by_name['RedisState'] = _REDISSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RedisState = _reflection.GeneratedProtocolMessageType('RedisState', (_message.Message,), {
  'DESCRIPTOR' : _REDISSTATE,
  '__module__' : 'orc8r.protos.redis_pb2'
  # @@protoc_insertion_point(class_scope:magma.orc8r.RedisState)
  })
_sym_db.RegisterMessage(RedisState)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
