# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orc8r/protos/streamer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='orc8r/protos/streamer.proto',
  package='magma.orc8r',
  syntax='proto3',
  serialized_options=b'Z\031magma/orc8r/lib/go/protos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1borc8r/protos/streamer.proto\x12\x0bmagma.orc8r\x1a\x19google/protobuf/any.proto\"a\n\rStreamRequest\x12\x11\n\tgatewayId\x18\x01 \x01(\t\x12\x13\n\x0bstream_name\x18\x02 \x01(\t\x12(\n\nextra_args\x18\x03 \x01(\x0b\x32\x14.google.protobuf.Any\"K\n\x0f\x44\x61taUpdateBatch\x12(\n\x07updates\x18\x01 \x03(\x0b\x32\x17.magma.orc8r.DataUpdate\x12\x0e\n\x06resync\x18\x02 \x01(\x08\"(\n\nDataUpdate\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\x32V\n\x08Streamer\x12J\n\nGetUpdates\x12\x1a.magma.orc8r.StreamRequest\x1a\x1c.magma.orc8r.DataUpdateBatch\"\x00\x30\x01\x42\x1bZ\x19magma/orc8r/lib/go/protosb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_STREAMREQUEST = _descriptor.Descriptor(
  name='StreamRequest',
  full_name='magma.orc8r.StreamRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gatewayId', full_name='magma.orc8r.StreamRequest.gatewayId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stream_name', full_name='magma.orc8r.StreamRequest.stream_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extra_args', full_name='magma.orc8r.StreamRequest.extra_args', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=168,
)


_DATAUPDATEBATCH = _descriptor.Descriptor(
  name='DataUpdateBatch',
  full_name='magma.orc8r.DataUpdateBatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='updates', full_name='magma.orc8r.DataUpdateBatch.updates', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resync', full_name='magma.orc8r.DataUpdateBatch.resync', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=245,
)


_DATAUPDATE = _descriptor.Descriptor(
  name='DataUpdate',
  full_name='magma.orc8r.DataUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='magma.orc8r.DataUpdate.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='magma.orc8r.DataUpdate.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=287,
)

_STREAMREQUEST.fields_by_name['extra_args'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_DATAUPDATEBATCH.fields_by_name['updates'].message_type = _DATAUPDATE
DESCRIPTOR.message_types_by_name['StreamRequest'] = _STREAMREQUEST
DESCRIPTOR.message_types_by_name['DataUpdateBatch'] = _DATAUPDATEBATCH
DESCRIPTOR.message_types_by_name['DataUpdate'] = _DATAUPDATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StreamRequest = _reflection.GeneratedProtocolMessageType('StreamRequest', (_message.Message,), {
  'DESCRIPTOR' : _STREAMREQUEST,
  '__module__' : 'orc8r.protos.streamer_pb2'
  # @@protoc_insertion_point(class_scope:magma.orc8r.StreamRequest)
  })
_sym_db.RegisterMessage(StreamRequest)

DataUpdateBatch = _reflection.GeneratedProtocolMessageType('DataUpdateBatch', (_message.Message,), {
  'DESCRIPTOR' : _DATAUPDATEBATCH,
  '__module__' : 'orc8r.protos.streamer_pb2'
  # @@protoc_insertion_point(class_scope:magma.orc8r.DataUpdateBatch)
  })
_sym_db.RegisterMessage(DataUpdateBatch)

DataUpdate = _reflection.GeneratedProtocolMessageType('DataUpdate', (_message.Message,), {
  'DESCRIPTOR' : _DATAUPDATE,
  '__module__' : 'orc8r.protos.streamer_pb2'
  # @@protoc_insertion_point(class_scope:magma.orc8r.DataUpdate)
  })
_sym_db.RegisterMessage(DataUpdate)


DESCRIPTOR._options = None

_STREAMER = _descriptor.ServiceDescriptor(
  name='Streamer',
  full_name='magma.orc8r.Streamer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=289,
  serialized_end=375,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetUpdates',
    full_name='magma.orc8r.Streamer.GetUpdates',
    index=0,
    containing_service=None,
    input_type=_STREAMREQUEST,
    output_type=_DATAUPDATEBATCH,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_STREAMER)

DESCRIPTOR.services_by_name['Streamer'] = _STREAMER

# @@protoc_insertion_point(module_scope)
